### ISSUE TITLE
Sobre mi [ 3 ]

### ISSUE THREAD

**Issue by Jaavii004** [Jaavii004/LOS-FIFA#13]
# Issue
Como: product Owner
Quiero: Poner su informacion detallada
Para:  poder ver quien es y tener mas informacion detallada
# Tareas
* Agregar una foto de la clienta.
* Sobre la imagen, una seccion de texto.
* Asegurarse de que el texto sea legible.

----> Editado por; Scrum master

**Comment by guyikcgg** [comment]
¿La información de quién queréis poner?
¿Cuál es la motivación? -- no se entiende
